const MILLISECONDS_IN_HOUR = 1000 * 60 * 60;
const MILLISECONDS_IN_DAY = MILLISECONDS_IN_HOUR * 24;
const MILLISECONDS_IN_WEEK = MILLISECONDS_IN_DAY * 7;

const MAX_NUM_OF_RESTAURANTS_TO_SHOW = 7;
const SUBSCRIPTION_EXPIRATION_HOURS = 4;

const SECONDS_BETWEEN_RESTAURANTS_REFRESH_OPTIONS = {
    FAST: 60 / 2,
    MEDIUM: 60,
    SLOW: 60 * 2,
    IDLE: 60 * 15,
};

const INITIAL_BOT_RESPONSE = `Hi {firstName}!\n\nI'm a bot that can alert you when a wolt restaurant opens\n\nYou can enter the restaurant name you want to check\n\nTo show current notification registrations please write: /show\n\n`;

const HOURS_DIFFERENCE_FROM_UTC = 2;

const MIN_HOUR_TO_ALERT_USER = 8;
const MAX_HOUR_TO_ALERT_USER = 23;

const RESTAURANTS_BASE_URL = 'https://consumer-api.wolt.com/v1/pages/restaurants';
const RESTAURANT_BASE_URL = 'https://consumer-api.wolt.com/order-xp/web/v1/venue/slug/{slug}/dynamic/';
const RESTAURANT_LINK_BASE_URL = 'https://wolt.com/en/isr/{area}/restaurant/{slug}';
const CITIES_BASE_URL = 'https://restaurant-api.wolt.com/v1/cities';

const CITIES_SLUGS_SUPPORTED = ['hasharon', 'tel-aviv'];
// 'afula-emek-yizrael-area',
// 'ashdod',
// 'ashkelon',
// 'beer-sheva',
// 'eilat',
// 'ness-ziona---rehovot',
// 'haifa',
// 'jerusalem',
// 'karmiel-area',
// 'kiryat-shmona-area',
// 'mevaseret-zion-area',
// 'modiin',
// 'nazareth---nof-hagalil-area',
// 'netanya',
// 'pardes-hanna',
// 'petah-tikva',
// 'rishon-lezion',
// 'rosh-pinna---zefat-area',
// 'yavne',
// 'yokneam',

const WOLT_BOT_OPTIONS = {
    START: '/start',
    SHOW: '/show',
};

const HOUR_OF_DAY_TO_REFRESH_MAP = {
    0: SECONDS_BETWEEN_RESTAURANTS_REFRESH_OPTIONS.SLOW,
    1: SECONDS_BETWEEN_RESTAURANTS_REFRESH_OPTIONS.SLOW,
    2: SECONDS_BETWEEN_RESTAURANTS_REFRESH_OPTIONS.SLOW,
    3: SECONDS_BETWEEN_RESTAURANTS_REFRESH_OPTIONS.SLOW,

    4: SECONDS_BETWEEN_RESTAURANTS_REFRESH_OPTIONS.IDLE,
    5: SECONDS_BETWEEN_RESTAURANTS_REFRESH_OPTIONS.IDLE,
    6: SECONDS_BETWEEN_RESTAURANTS_REFRESH_OPTIONS.IDLE,
    7: SECONDS_BETWEEN_RESTAURANTS_REFRESH_OPTIONS.IDLE,
    8: SECONDS_BETWEEN_RESTAURANTS_REFRESH_OPTIONS.IDLE,
    9: SECONDS_BETWEEN_RESTAURANTS_REFRESH_OPTIONS.IDLE,
    10: SECONDS_BETWEEN_RESTAURANTS_REFRESH_OPTIONS.IDLE,

    11: SECONDS_BETWEEN_RESTAURANTS_REFRESH_OPTIONS.FAST,
    12: SECONDS_BETWEEN_RESTAURANTS_REFRESH_OPTIONS.FAST,
    13: SECONDS_BETWEEN_RESTAURANTS_REFRESH_OPTIONS.FAST,
    14: SECONDS_BETWEEN_RESTAURANTS_REFRESH_OPTIONS.FAST,
    15: SECONDS_BETWEEN_RESTAURANTS_REFRESH_OPTIONS.FAST,

    16: SECONDS_BETWEEN_RESTAURANTS_REFRESH_OPTIONS.MEDIUM,
    17: SECONDS_BETWEEN_RESTAURANTS_REFRESH_OPTIONS.MEDIUM,

    18: SECONDS_BETWEEN_RESTAURANTS_REFRESH_OPTIONS.FAST,
    19: SECONDS_BETWEEN_RESTAURANTS_REFRESH_OPTIONS.FAST,
    20: SECONDS_BETWEEN_RESTAURANTS_REFRESH_OPTIONS.FAST,
    21: SECONDS_BETWEEN_RESTAURANTS_REFRESH_OPTIONS.FAST,
    22: SECONDS_BETWEEN_RESTAURANTS_REFRESH_OPTIONS.FAST,
    23: SECONDS_BETWEEN_RESTAURANTS_REFRESH_OPTIONS.FAST,
};

const ANALYTIC_EVENT_NAMES = {
    START: 'START',
    SHOW: 'SHOW',
    SEARCH: 'SEARCH',
    SUBSCRIBE: 'SUBSCRIBE',
    UNSUBSCRIBE: 'UNSUBSCRIBE',
    SUBSCRIPTION_FULFILLED: 'SUBSCRIPTION_FULFILLED',
    SUBSCRIPTION_FAILED: 'SUBSCRIPTION_FAILED',
    ERROR: 'ERROR',
};

module.exports = {
    MILLISECONDS_IN_HOUR,
    MILLISECONDS_IN_DAY,
    MILLISECONDS_IN_WEEK,
    MAX_NUM_OF_RESTAURANTS_TO_SHOW,
    SUBSCRIPTION_EXPIRATION_HOURS,
    SECONDS_BETWEEN_RESTAURANTS_REFRESH_OPTIONS,
    INITIAL_BOT_RESPONSE,
    HOURS_DIFFERENCE_FROM_UTC,
    MIN_HOUR_TO_ALERT_USER,
    MAX_HOUR_TO_ALERT_USER,
    RESTAURANTS_BASE_URL,
    RESTAURANT_BASE_URL,
    RESTAURANT_LINK_BASE_URL,
    CITIES_BASE_URL,
    CITIES_SLUGS_SUPPORTED,
    WOLT_BOT_OPTIONS,
    HOUR_OF_DAY_TO_REFRESH_MAP,
    ANALYTIC_EVENT_NAMES,
};
