const OPENAI_API_KEY = process.env.OPEN_AI_API_KEY;
const CHAT_COMPLETIONS_MODEL = 'gpt-4o';
const SOUND_MODEL = 'whisper-1';
const IMAGE_GENERATION_MODEL = 'dall-e-3';
const TEXT_TO_SPEECH_MODEL = 'tts-1';
const TEXT_TO_SPEECH_VOICE = 'shimmer';

module.exports = {
    OPENAI_API_KEY,
    CHAT_COMPLETIONS_MODEL,
    SOUND_MODEL,
    IMAGE_GENERATION_MODEL,
    TEXT_TO_SPEECH_MODEL,
    TEXT_TO_SPEECH_VOICE,
};
